[package]
name = "RustyUsn"
version = "0.5.0"
authors = ["Matthew Seyer <https://github.com/forensicmatt/RustyUsn>"]

[lib]
name = "rustyusn"
crate-type = ["cdylib","lib"]

[dependencies]
lazy_static = "*"
regex = "0.1.80"
byteorder = "*"
clap = "*"
time = "*"
seek_bufread = "~1.2"
bitflags = "0.7"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
jmespath = "^0.1.1"

[dependencies.r-winstructs]
version = "*"
branch = "master"
git = "https://github.com/forensicmatt/r-winstructs"

[dependencies.chrono]
version = "*"
features = ["serde", "rustc-serialize"]

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]
