[package]
name = "RusyUsn"
version = "0.3.0"
authors = ["forensicmatt <matthew.seyer@gmail.com>"]

[lib]
name = "rustyusn"
crate-type = ["cdylib","lib"]

[dependencies]
lazy_static = "*"
regex = "0.1.80"
byteorder = "*"
clap = "*"
time = "*"
seek_bufread = "~1.2"
bitflags = "0.7"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.chrono]
version = "*"
features = ["serde", "rustc-serialize"]

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]
