[package]
name = "rusty_usn"
version = "0.1.0"
authors = ["forensicmatt <matthew.seyer@gmail.com>"]

[lib]
name = "rustyusn"
crate-type = ["cdylib","lib"]

[dependencies]
lazy_static = "*"
regex = "*"
byteorder = "*"
clap = "*"

[dependencies.chrono]
version = "*"
features = ["serde", "rustc-serialize"]

[dependencies.cpython]
version = "*"
default-features = false
features = ["python27-sys"]
